using System;
using Rb.Core.Components;

namespace Rb.Interaction
{
	/// <summary>
	/// Objects of this class subscribe to events generated by commands from a specified command list. These commands are turned into CommandMessage objects
	/// and sent to the parent object
	/// </summary>
	public class CommandInputListener : IChild
    {
        #region Construction

        /// <summary>
        /// Default constructor
        /// </summary>
        public CommandInputListener( )
        {
        }

        /// <summary>
        /// Setup constructor
        /// </summary>
        public CommandInputListener( object target, CommandUser user, CommandList commands )
        {
			m_Target	= target;
			m_Commands	= commands;
			User		= user;
        }

		/// <summary>
		/// Setup constructor
		/// </summary>
		public CommandInputListener( object target, CommandUser user, string commandListName )
		{
			m_Target = target;
			CommandListName = commandListName;
			User = user;
		}

        #endregion

        #region	Command list

		/// <summary>
		/// Sets the name of the comand list to use
		/// </summary>
		public string CommandListName
		{
			set
			{
				Unlisten( m_User );
				m_Commands = CommandListManager.Instance.Get( value );
				Listen( m_User, m_Commands );
			}
		}

		/// <summary>
		/// Sets the enum type of the comand list to use
		/// </summary>
		public Type CommandListEnumType
		{
			set
			{
				Unlisten( m_User );
				m_Commands = CommandListManager.Instance.FindOrCreateFromEnum( value );
				Listen( m_User, m_Commands );
			}
		}

        /// <summary>
		/// Sets the command list that this object is associated with
		/// </summary>
		public CommandUser User
		{
			set
			{
				Unlisten( m_User );
				m_User = value;
				Listen( m_User, m_Commands );
			}
			get
			{
				return m_User;
			}
		}

		#endregion

		#region Public properties

		/// <summary>
		/// Command messages are sent to this object. If it's not set, it defaults to the parent object
		/// </summary>
		public object Target
		{
			get { return m_Target; }
			set { m_Target = value; }
		}

		#endregion

		#region IChild Members

		/// <summary>
		/// Called when this object is added to a parent
		/// </summary>
		public void AddedToParent( Object parentObject )
		{
			if ( Target == null )
			{
				Target = parentObject;
			}
		}

		#endregion

		#region	Private stuff

		private object		m_Target;
		private CommandUser	m_User;
		private CommandList m_Commands;


		/// <summary>
		/// Called when a command is activated
		/// </summary>
		private void CommandActivated( CommandMessage message )
		{
			if ( Target != null )
			{
				( ( IMessageHandler )Target ).HandleMessage( message );
			}
		}

		/// <summary>
		/// Called when a command is active
		/// </summary>
		private void CommandActive( CommandMessage message )
		{
			if ( Target != null )
			{
				( ( IMessageHandler )Target ).HandleMessage( message );
			}
		}

		/// <summary>
		/// Stops listen for command messages from a given user
		/// </summary>
		private void Unlisten( CommandUser user )
		{
			if ( user != null )
			{
				user.RemoveListener( CommandActivated );
				user.RemoveListener( CommandActive );
			}
		}

		/// <summary>
		/// Starts listening for command messages (from a specified command list) from a given user
		/// </summary>
		private void Listen( CommandUser user, CommandList commands )
		{
			if ( ( user != null ) && ( commands != null ) )
			{
				user.AddActivatedListener( commands, CommandActivated );
				user.AddActiveListener( commands, CommandActive );
			}
		}

		#endregion

	}
}
