
samplerCUBE CloudTexture = sampler_state
{
	WrapS = ClampToEdge;
	WrapT = ClampToEdge;
	WrapR = ClampToEdge;
	MinFilter = Linear;
	MagFilter = Linear;
};

samplerCUBE NextCloudTexture = sampler_state
{
	WrapS = ClampToEdge;
	WrapT = ClampToEdge;
	WrapR = ClampToEdge;
	MinFilter = Linear;
	MagFilter = Linear;
};

float4x4 CloudTransform = { { 1, 0, 0, 0 }, { 0, 1, 0, 0 }, { 0, 0, 1, 0 }, { 0, 0, 0, 1 } };
float CloudBlend = 0;

float4 GetCloudCover( float3 sphereNormal )
{
	float4 cloudNormal = mul( CloudTransform, float4( sphereNormal, 1 ) );

	float4 curCloud = texCUBE( CloudTexture, cloudNormal );
	float4 nextCloud = texCUBE( NextCloudTexture, cloudNormal );

	return ( ( nextCloud * CloudBlend ) + ( curCloud * ( 1 - CloudBlend ) ) );
}