using Poc1.Core.Interfaces;
using Poc1.Core.Interfaces.Astronomical.Planets.Models;

namespace Poc1.Core.Classes.Astronomical.Planets.Models
{
	/// <summary>
	/// Planet terrain model
	/// </summary>
	public class PlanetTerrainModel : AbstractPlanetEnvironmentModel, IPlanetTerrainModel
	{
		#region IPlanetTerrainModel Members

		/// <summary>
		/// Gets/sets the maximum height of terrain generated by this model
		/// </summary>
		/// <remarks>
		/// On set, the ModelChanged event is invoked.
		/// </remarks>
		public Units.Metres MaximumHeight
		{
			get { return m_MaximumHeight; }
			set
			{
				if ( m_MaximumHeight != value )
				{
					m_MaximumHeight = value;
					OnModelChanged( );
				}
			}
		}

		#endregion

		#region Private Members

		private Units.Metres m_MaximumHeight = new Units.Metres( 5000 );

		#endregion
	}
}
