//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rb.Tools.LevelEditor.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rb.Tools.LevelEditor.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Creates object.
        /// </summary>
        internal static string AddObjectInputs {
            get {
                return ResourceManager.GetString("AddObjectInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t load asset into type &quot;{0}&quot;.
        /// </summary>
        internal static string CantLoadAssetIntoType {
            get {
                return ResourceManager.GetString("CantLoadAssetIntoType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorCaption {
            get {
                return ResourceManager.GetString("ErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding new object to scene.
        /// </summary>
        internal static string FailedToAddObject {
            get {
                return ResourceManager.GetString("FailedToAddObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to export scene to file &quot;{0}&quot;.
        /// </summary>
        internal static string FailedToExportScene {
            get {
                return ResourceManager.GetString("FailedToExportScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open scene file &quot;{0}&quot;.
        /// </summary>
        internal static string FailedToOpenScene {
            get {
                return ResourceManager.GetString("FailedToOpenScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save scene to file &quot;{0}&quot;.
        /// </summary>
        internal static string FailedToSaveScene {
            get {
                return ResourceManager.GetString("FailedToSaveScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string LeftMouseButton {
            get {
                return ResourceManager.GetString("LeftMouseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} properties.
        /// </summary>
        internal static string LoaderProperties {
            get {
                return ResourceManager.GetString("LoaderProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle.
        /// </summary>
        internal static string MiddleMouseButton {
            get {
                return ResourceManager.GetString("MiddleMouseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Moves selected objects.
        /// </summary>
        internal static string MoveInputs {
            get {
                return ResourceManager.GetString("MoveInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No asset location managers with UI were available.
        /// </summary>
        internal static string NoLocationManagersWithUI {
            get {
                return ResourceManager.GetString("NoLocationManagersWithUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        internal static string RightMouseButton {
            get {
                return ResourceManager.GetString("RightMouseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Selects object.
        /// </summary>
        internal static string SelectInputs {
            get {
                return ResourceManager.GetString("SelectInputs", resourceCulture);
            }
        }
    }
}
