using System;
using System.Collections;

namespace RbEngine.Interaction
{
	/// <summary>
	/// A Runt IServerUpdater. Sends command messages generated by Interaction.Command objects to a server
	/// </summary>
	public class CommandServerUpdater : Network.Runt.IServerUpdater, Components.IChildObject, Scene.ISceneObject
	{
		#region IServerUpdater Members

		/// <summary>
		/// Handles update messages sent to the server
		/// </summary>
		public void HandleServerUpdate( RbEngine.Network.Runt.UpdateMessage msg )
		{
		}

		/// <summary>
		/// Gets update messages to send to the client
		/// </summary>
		public void GetUpdateMessages( System.Collections.ArrayList messages )
		{
			Components.ObjectId id = ( ( Components.IUnique )m_Parent ).Id;
			foreach ( Components.Message msg in m_Messages )
			{
				messages.Add( new Network.Runt.WrapUpdateMessage( id, msg ) );
			}
			m_Messages.Clear( );
		}

		#endregion

		#region IChildObject Members

		/// <summary>
		/// Called when this object is added to a parent object. The parent object is the command message source for this object
		/// </summary>
		public void AddedToParent( Object parentObject )
		{
			m_Parent = parentObject;

			( ( Components.IMessageHandler )m_Parent ).AddRecipient( typeof( CommandMessage ), new Components.MessageRecipientDelegate( ReceivedCommandMessage ), ( int )Components.MessageRecipientOrder.First );
		}

		#endregion

		#region ISceneObject Members

		/// <summary>
		/// Called when this object is added to the scene
		/// </summary>
		public void AddedToScene( Scene.SceneDb db )
		{
			//	Add this updater to the server updater
			Network.Runt.ServerUpdateManager updateManager = ( Network.Runt.ServerUpdateManager )db.GetSystem( typeof( Network.Runt.ServerUpdateManager ) );
			if ( updateManager == null )
			{
				throw new ApplicationException( "CommandServerUpdater requires a ServerUpdateManager to present in the scene systems" );
			}

			updateManager.AddUpdater( this );
		}

		/// <summary>
		/// Called when this object is removed from the scene
		/// </summary>
		public void RemovedFromScene( Scene.SceneDb db )
		{
		}

		#endregion

		#region	Private stuff

		private Object		m_Parent;
		private ArrayList	m_Messages = new ArrayList( );

		/// <summary>
		/// Called when this object receives a command message
		/// </summary>
		private Components.MessageRecipientResult ReceivedCommandMessage( Components.Message msg )
		{
			//	TODO: Should be a fixed size buffer
			m_Messages.Add( msg );
			return Components.MessageRecipientResult.DeliverToNext;
		}

		#endregion

	}
}
