
namespace Poc1.Core.Interfaces.Astronomical.Planets.Models
{
	/// <summary>
	/// Planetary terrain model
	/// </summary>
	public interface IPlanetTerrainModel : IPlanetEnvironmentModel
	{
		/// <summary>
		/// Gets/sets the maximum height of terrain generated by this model
		/// </summary>
		/// <remarks>
		/// On set, the ModelChanged event is invoked.
		/// </remarks>
		Units.Metres MaximumHeight
		{
			get; set;
		}
	}
}
